# Generated by Django 5.2.3 on 2025-06-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_person_document_date_person_document_given_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='document_given_by',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
